-- CreateTable
CREATE TABLE "User" (
    "USERID" SERIAL NOT NULL,
    "EMAIL" TEXT NOT NULL,
    "USERNAME" TEXT NOT NULL,
    "USERPASSWORD" TEXT NOT NULL,
    "CreateAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updateAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "User_pkey" PRIMARY KEY ("USERID")
);

-- CreateTable
CREATE TABLE "Wallet" (
    "WALLETID" SERIAL NOT NULL,
    "USERID" INTEGER NOT NULL,
    "TOTALBALANCE" INTEGER NOT NULL,
    "TRANSACTIONID" INTEGER,

    CONSTRAINT "Wallet_pkey" PRIMARY KEY ("WALLETID")
);

-- CreateTable
CREATE TABLE "Transaction" (
    "TRANSACTIONID" SERIAL NOT NULL,
    "USERID" INTEGER NOT NULL,
    "WALLETID" INTEGER NOT NULL,
    "TYPE" TEXT NOT NULL,
    "AMOUNT" INTEGER NOT NULL,
    "CATEGORY" TEXT NOT NULL,
    "NOTE" TEXT NOT NULL,

    CONSTRAINT "Transaction_pkey" PRIMARY KEY ("TRANSACTIONID")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_EMAIL_key" ON "User"("EMAIL");

-- CreateIndex
CREATE UNIQUE INDEX "User_USERNAME_key" ON "User"("USERNAME");

-- AddForeignKey
ALTER TABLE "Wallet" ADD CONSTRAINT "Wallet_USERID_fkey" FOREIGN KEY ("USERID") REFERENCES "User"("USERID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Transaction" ADD CONSTRAINT "Transaction_USERID_fkey" FOREIGN KEY ("USERID") REFERENCES "User"("USERID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Transaction" ADD CONSTRAINT "Transaction_WALLETID_fkey" FOREIGN KEY ("WALLETID") REFERENCES "Wallet"("WALLETID") ON DELETE RESTRICT ON UPDATE CASCADE;
